<$PLAN9/src/mkhdr
# chicanery is the version of electron that uses plan9port
TARG=chicanery
BIN=$ELECTRON_PLATFORM_ROOT/sys/bin
LDFLAGS="-lrt -lm -lc -L/usr/lib"
CFLAGS=-Os -I$ELECTRON_PLATFORM_ROOT/sys/include -I/usr/include
LIBELECTRON=$ELECTRON_PLATFORM_ROOT/sys/src/electron
LIB=$ELECTRON_PLATFORM_ROOT/sys/src/
LIBEFSSRV=$LIB/libefs
LIBEVT=$LIB/libevt
LIBEDRAW=$LIB/libedraw
LIB=$LIBELECTRON/libelectron9.a $LIBEFSSRV/libefs.a $LIBEVT/libevt.a $LIBEDRAW/libedraw.a

OFILES=\
       chicanery.$O\
       reroute.$O\
       userfunctions.$O\

<$PLAN9/src/mkone
