<$PLAN9/src/mkhdr

LIB=libsrvevt.a
LDFLAGS="-lrt -lm -lc -L/usr/lib"
CFLAGS=-Os -I$ELECTRON_PLATFORM_ROOT/sys/include -I/usr/include

OFILES=\
       mouse.$O\

HFILES=\
      evt.h\


<$PLAN9/src/mklib
