<$PLAN9/src/mkhdr
BIN=$ELECTRON_PLATFORM_ROOT/sys/bin
LDFLAGS="-lrt -lm -lc -L/usr/lib"
CFLAGS=-Os -I$ELECTRON_PLATFORM_ROOT/sys/include -I/usr/include
LIBELECTRON=$ELECTRON_PLATFORM_ROOT/sys/src/electron
LIBEFSSRV=$ELECTRON_PLATFORM_ROOT/sys/src/srv/efs
DIRS = electron\
       srv/efs\
       lib/evt\
       lib/edraw\
       cmd/chicanery\

<$PLAN9/src/mkdirs
